// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern void void name_field_CB(name_input*, void*);
extern name_input *name_field;
#include <FL/Fl_Dial.H>
Fl_Double_Window* make_window();
#endif
