#!/usr/local/bin/bash

export LESSCHARSET="utf-8"
export LANG=en_GB.UTF-8
export TERM="mlterm"
setxkbmap -layout gb,ir -option "grp:alt_shift_toggle" -compat "group_led"
mlterm --sl 1024 -K alt --bg black --fg white -E utf8 -w 20 -s=false -ls

