#!/usr/local/bin/bash

export LESSCHARSET="utf-8"
export LANG=en_US.UTF-8
setxkbmap -layout gb,ir -option "grp:alt_shift_toggle" -compat "group_led"
/usr/local/src/mlterm-2.9.2/xwindow/mlterm --sl 1024 -K alt --bg black --fg white -E utf8 -w 20 -s=false -ls -e mutt

